"""add delivery response fields

Revision ID: 3badaef1b7f3
Revises: ed0fbae99290
Create Date: 2026-07-10 22:52:34.116630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3badaef1b7f3'
down_revision: Union[str, Sequence[str], None] = 'ed0fbae99290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_events', sa.Column('response_status_code', sa.Integer(), nullable=True))
    op.add_column('webhook_events', sa.Column('response_body', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhook_events', 'response_body')
    op.drop_column('webhook_events', 'response_status_code')
    # ### end Alembic commands ###
