"""add webhook secret

Revision ID: 93266bf015b8
Revises: c3eac6612ada
Create Date: 2026-07-08 23:32:34.445556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93266bf015b8'
down_revision: Union[str, Sequence[str], None] = 'c3eac6612ada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhooks', sa.Column('secret', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_webhooks_secret'), 'webhooks', ['secret'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhooks_secret'), table_name='webhooks')
    op.drop_column('webhooks', 'secret')
    # ### end Alembic commands ###
