"""add payload json

Revision ID: ed0fbae99290
Revises: 2ecd30e3a2b3
Create Date: 2026-07-10 22:26:51.094356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed0fbae99290'
down_revision: Union[str, Sequence[str], None] = '2ecd30e3a2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_events', sa.Column('payload_json', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhook_events', 'payload_json')
    # ### end Alembic commands ###
